
name: 'AutoRealeseMilestone'
description: 'My Desc'
author: 'Ich'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the current repository'
    required: true
outputs:
  release-url:              # change this
    description: 'The URL of the GitHub drafted release'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}